apiVersion: v1
kind: Pod
metadata:
  name: data-loader
  namespace: database
spec:
  containers:
    - name: loader
      image: busybox
      command:
        - sleep
        - "3600"
      volumeMounts:
        - name: data
          mountPath: /workspace/data
  volumes:
    - name: data
      persistentVolumeClaim:
        claimName: data-pvc
