apiVersion: batch/v1
kind: Job
metadata:
  name: etl
  namespace: database
spec:
  backoffLimit: 1
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: etl
          image: etl:local
          imagePullPolicy: IfNotPresent
