apiVersion: apps/v1
kind: Deployment
metadata:
  name: jobmanager
  namespace: database
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jobmanager
  template:
    metadata:
      labels:
        app: jobmanager
    spec:
      containers:
        - name: jobmanager
          image: flink:local
          imagePullPolicy: IfNotPresent
          args: ["jobmanager"]
          ports:
            - containerPort: 8081
          env:
            - name: FLINK_PROPERTIES
              value: |
                jobmanager.rpc.address: jobmanager
          volumeMounts:
            - name: flink-sql
              mountPath: /opt/flink/sql/run.sql
              subPath: run.sql
            - name: flink-sql
              mountPath: /opt/flink/sql/generated/01-source.sql
              subPath: 01-source.sql
            - name: flink-sql
              mountPath: /opt/flink/sql/generated/02-sink.sql
              subPath: 02-sink.sql
            - name: flink-sql
              mountPath: /opt/flink/sql/generated/03-transform.sql
              subPath: 03-transform.sql
            - name: flink-config
              mountPath: /opt/flink/conf/config.yaml
              subPath: config.yaml

      volumes:
        - name: flink-sql
          configMap:
            name: flink-sql-configmap

        - name: flink-config
          configMap:
            name: flink-config
---
apiVersion: v1
kind: Service
metadata:
  name: jobmanager
  namespace: database
spec:
  selector:
    app: jobmanager
  ports:
    - name: rpc
      port: 6123
      targetPort: 6123
    - name: ui
      port: 8081
      targetPort: 8081
