"""create initial tables

Revision ID: 0a9a29d08f7f
Revises: 
Create Date: 2026-07-15 11:20:29.452865

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0a9a29d08f7f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('locations',
    sa.Column('location_id', sa.Integer(), nullable=False),
    sa.Column('borough', sa.String(), nullable=True),
    sa.Column('zone', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('location_id')
    )
    op.create_table('taxi_trips',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vendor_id', sa.Integer(), nullable=True),
    sa.Column('pickup_datetime', sa.DateTime(), nullable=True),
    sa.Column('dropoff_datetime', sa.DateTime(), nullable=True),
    sa.Column('passenger_count', sa.Integer(), nullable=True),
    sa.Column('trip_distance', sa.Float(), nullable=True),
    sa.Column('pickup_location_id', sa.Integer(), nullable=True),
    sa.Column('dropoff_location_id', sa.Integer(), nullable=True),
    sa.Column('fare_amount', sa.Float(), nullable=True),
    sa.Column('tip_amount', sa.Float(), nullable=True),
    sa.Column('total_amount', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['dropoff_location_id'], ['locations.location_id'], ),
    sa.ForeignKeyConstraint(['pickup_location_id'], ['locations.location_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('predictions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('trip_id', sa.Integer(), nullable=True),
    sa.Column('model_version', sa.String(), nullable=True),
    sa.Column('predicted_duration', sa.Float(), nullable=True),
    sa.Column('prediction_time', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['trip_id'], ['taxi_trips.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('predictions')
    op.drop_table('taxi_trips')
    op.drop_table('locations')
    # ### end Alembic commands ###
