apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "logistics.fullname" . }}-postgres-pvc
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "logistics.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.postgres.persistence.size }}
