apiVersion: v1
kind: Secret
metadata:
  name: {{ include "logistics.fullname" . }}-ghcr-pull-secret
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "logistics.labels" . | nindent 4 }}
type: kubernetes.io/dockerconfigjson
stringData:
  .dockerconfigjson: |-
    {{ printf "{\"auths\":{\"ghcr.io\":{\"username\":\"%s\",\"password\":\"%s\",\"auth\":\"%s\"}}}" .Values.global.ghcr.username .Values.global.ghcr.token (printf "%s:%s" .Values.global.ghcr.username .Values.global.ghcr.token | b64enc) }}
